name: Push to docker hub

on:
push:
  branches:[ master ]
pull_request:
  branches:[ master ]
 
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v3
      - name: Push
        run: |
          docker push ayobami6/peers_dev_container:v1
